[package]
name = "opengl"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy_ecs = "0.9.1"
gl = "0.14.0"
glfw = "0.51.0"
image = "0.24.5"
tobj = "3.2.4"
ultraviolet = "0.9.0"
